-- Add missing saigon category
INSERT INTO public.categories (id, label, icon, description, sort_order)
VALUES ('saigon', 'Ô Little Saigon', '🌶️', 'Tapas vietnamiennes & street food', 4)
ON CONFLICT (id) DO NOTHING;

UPDATE public.categories SET label = 'Cantina America', icon = '🍔', description = 'Burgers signature & viandes grillées' WHERE id = 'cantina';

INSERT INTO public.menu_items (id, category_id, name, price, description, volume, subcategory, image_url, badges, is_available, sort_order) VALUES
('cocktail-pivoine', 'jardins', 'Pivoine', 12, 'Gin, Aperol, citronnade, jus d''ananas.', '20cl', 'Cocktails Créations', 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&h=600&fit=crop', ARRAY['Signature']::TEXT[], true, 1),
('cocktail-dahlia', 'jardins', 'Dahlia', 12, 'Rhum, purée de framboise, jus d''ananas, citron.', '20cl', 'Cocktails Créations', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&h=600&fit=crop', ARRAY['Signature']::TEXT[], true, 2),
('cocktail-bouton-or', 'jardins', 'Bouton d''Or', 12, 'Vodka, prosecco, citron, sucre, basilic.', '16cl', 'Cocktails Créations', 'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 3),
('cocktail-fleur-lys', 'jardins', 'Fleur de Lys', 12, 'Whisky, sirop de gingembre, ginger beer, citron.', '16cl', 'Cocktails Créations', 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 4),
('cocktail-le-two', 'jardins', 'Le Two — Cocktail du Moment', 13, 'Gin, purée de fraise, sucre, citron. La création du moment 🍓', '14cl', 'Cocktails Créations', 'https://images.unsplash.com/photo-1560512823-829485b8bf24?w=600&h=600&fit=crop', ARRAY['Best-Seller']::TEXT[], true, 5),
('classic-bellini', 'jardins', 'Bellini', 8.5, 'Prosecco & purée de pêche blanche.', '14cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 10),
('classic-rossini', 'jardins', 'Rossini', 8.5, 'Prosecco & purée de fraise fraîche.', '14cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 11),
('classic-cuba-libre', 'jardins', 'Cuba Libre', 8.5, 'Rhum, coca, citron vert.', '20cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 12),
('classic-negroni', 'jardins', 'Negroni', 8.5, 'Gin, Campari, vermouth rouge.', '9cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 13),
('classic-expresso-martini', 'jardins', 'Expresso Martini', 11, 'Vodka, liqueur de café, expresso frais.', '16cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 14),
('classic-margarita', 'jardins', 'Margarita', 10, 'Tequila, triple sec, citron vert, sel.', '16cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 15),
('classic-gin-tonic', 'jardins', 'Gin Tonic', 10, 'Gin premium & tonic water.', '16cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 16),
('classic-aperol-spritz', 'jardins', 'Aperol Spritz', 10, 'Aperol, prosecco, eau pétillante, orange.', '16cl', 'Cocktails Classiques', NULL, ARRAY['Best-Seller']::TEXT[], true, 17),
('classic-stgermain-spritz', 'jardins', 'St Germain Spritz', 12, 'St Germain, prosecco, eau pétillante.', '16cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 18),
('classic-jamaican-mule', 'jardins', 'Jamaican Mule', 11, 'Rhum, ginger beer, citron vert.', '12cl', 'Cocktails Classiques', NULL, ARRAY[]::TEXT[], true, 19),
('mock-virgin-gin-tonic', 'jardins', 'Virgin Gin Tonic', 7.5, 'Sans alcool. Tonic, citron, herbes fraîches.', '16cl', 'Mocktails', NULL, ARRAY['Sans Alcool']::TEXT[], true, 30),
('mock-sakura', 'jardins', 'Sakura', 7.5, 'Sirop de cerise, pamplemousse, jus de pomme, citron.', '12cl', 'Mocktails', NULL, ARRAY['Sans Alcool']::TEXT[], true, 31),
('mock-virgin-jamaican', 'jardins', 'Virgin Jamaican Mule', 7.5, 'Rhum zéro, ginger beer, citron, sucre.', '12cl', 'Mocktails', NULL, ARRAY['Sans Alcool']::TEXT[], true, 32),
('mock-multi-jardins', 'jardins', 'Multi Jardins', 7.5, 'Jus de pomme, fruits rouges, mangue, citron.', '16cl', 'Mocktails', NULL, ARRAY['Sans Alcool']::TEXT[], true, 33),
('mock-wonka', 'jardins', 'Wonka', 7.5, 'Purée de fraises, sirop de chocolat maison, jus de pomme. 🎫', '17cl', 'Mocktails', NULL, ARRAY['Sans Alcool']::TEXT[], true, 34),
('soft-coca', 'jardins', 'Coca-Cola', 3.5, 'Coca-Cola classique bien frais.', '50cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 50),
('soft-orangina', 'jardins', 'Orangina', 4, 'L''incontournable secouez-moi !', '25cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 51),
('soft-sprite', 'jardins', 'Sprite', 3.5, 'Limonade citron-citron vert.', '50cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 52),
('soft-sirop', 'jardins', 'Sirop à l''eau', 2, 'Au choix : grenadine, menthe, fraise.', '33cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 53),
('soft-the-glace', 'jardins', 'Thé Glacé Maison', 3.5, 'Infusion fraîche, citron & menthe du jardin.', '20cl', 'Softs', NULL, ARRAY['Maison']::TEXT[], true, 54),
('soft-citronnade', 'jardins', 'Citronnade Maison', 4, 'Citrons pressés, eau, sucre de canne.', '20cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 55),
('soft-ginger-beer', 'jardins', 'Ginger Beer', 4, 'Boisson au gingembre piquante.', '20cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 56),
('soft-perrier', 'jardins', 'Perrier', 4, 'Eau gazeuse minérale.', '33cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 57),
('soft-san-pellegrino', 'jardins', 'San Pellegrino', 4, 'Eau gazeuse italienne, finement pétillante.', '75cl', 'Softs', NULL, ARRAY[]::TEXT[], true, 58),
('soft-edena', 'jardins', 'Edena Plate', 3, 'Eau plate de La Réunion 🏝️', '1L', 'Softs', NULL, ARRAY['100% Péi']::TEXT[], true, 59),
('biere-heineken-25', 'jardins', 'Heineken (25cl)', 3.5, 'Pression Heineken, mousse onctueuse.', '25cl', 'Bières Pression', NULL, ARRAY[]::TEXT[], true, 70),
('biere-heineken-50', 'jardins', 'Heineken (50cl)', 6, 'Pression Heineken format pinte.', '50cl', 'Bières Pression', NULL, ARRAY[]::TEXT[], true, 71),
('biere-heineken-3l', 'jardins', 'Heineken Tour 3L', 30, 'Tour de bière Heineken — pour la table 🍻', '3L', 'Bières Pression', NULL, ARRAY['À partager']::TEXT[], true, 72),
('biere-affligem-25', 'jardins', 'Affligem Blonde (25cl)', 4.5, 'Bière d''abbaye blonde, ronde et fruitée.', '25cl', 'Bières Pression', NULL, ARRAY[]::TEXT[], true, 73),
('biere-affligem-50', 'jardins', 'Affligem Blonde (50cl)', 8.5, 'Pinte Affligem Blonde.', '50cl', 'Bières Pression', NULL, ARRAY[]::TEXT[], true, 74),
('biere-kewes-rouge-25', 'jardins', 'Kewes Rouge (25cl)', 4, 'Bière artisanale péi, malts torréfiés. 🏝️', '25cl', 'Bières Pression', NULL, ARRAY['100% Péi']::TEXT[], true, 75),
('biere-kewes-rouge-50', 'jardins', 'Kewes Rouge (50cl)', 8, 'Pinte Kewes Rouge artisanale.', '50cl', 'Bières Pression', NULL, ARRAY['100% Péi']::TEXT[], true, 76),
('biere-kewes-blanche-25', 'jardins', 'Kewes Blanche (25cl)', 4, 'Blanche péi, légère et désaltérante.', '25cl', 'Bières Pression', NULL, ARRAY['100% Péi']::TEXT[], true, 77),
('biere-kewes-blanche-50', 'jardins', 'Kewes Blanche (50cl)', 8, 'Pinte Kewes Blanche péi.', '50cl', 'Bières Pression', NULL, ARRAY['100% Péi']::TEXT[], true, 78),
('biere-btl-heineken', 'jardins', 'Heineken Bouteille', 4, 'Bouteille Heineken servie fraîche.', '25cl', 'Bières Bouteille', NULL, ARRAY[]::TEXT[], true, 90),
('biere-btl-heineken-0', 'jardins', 'Heineken 0%', 4, 'Sans alcool, même goût.', '25cl', 'Bières Bouteille', NULL, ARRAY['Sans Alcool']::TEXT[], true, 91),
('hot-expresso', 'jardins', 'Expresso', 2, 'Café serré 100% arabica.', NULL, 'Boissons Chaudes', NULL, ARRAY[]::TEXT[], true, 100),
('hot-decafeine', 'jardins', 'Décaféiné', 2, 'Expresso sans caféine.', NULL, 'Boissons Chaudes', NULL, ARRAY[]::TEXT[], true, 101),
('hot-noisette', 'jardins', 'Noisette', 2.2, 'Expresso avec une touche de lait.', NULL, 'Boissons Chaudes', NULL, ARRAY[]::TEXT[], true, 102),
('hot-cappuccino', 'jardins', 'Cappuccino', 3.8, 'Expresso, lait moussé, cacao.', NULL, 'Boissons Chaudes', NULL, ARRAY[]::TEXT[], true, 103),
('hot-the', 'jardins', 'Thé', 3, 'Sélection de thés et infusions.', NULL, 'Boissons Chaudes', NULL, ARRAY[]::TEXT[], true, 104),
('alc-ricard', 'jardins', 'Ricard', 4, 'Pastis de Marseille, à allonger d''eau fraîche.', '4cl', 'Alcools', NULL, ARRAY[]::TEXT[], true, 120),
('alc-martini', 'jardins', 'Martini Blanc / Rouge', 5, 'Vermouth italien, blanc ou rouge au choix.', '6cl', 'Alcools', NULL, ARRAY[]::TEXT[], true, 121),
('alc-vodka-ketel', 'jardins', 'Vodka Ketel One', 10, 'Vodka premium hollandaise.', '6cl', 'Alcools', NULL, ARRAY[]::TEXT[], true, 122),
('alc-tequila-don-julio', 'jardins', 'Tequila Don Julio', 14, 'Tequila 100% agave, méthode artisanale.', '6cl', 'Alcools', NULL, ARRAY['Premium']::TEXT[], true, 123),
('alc-rhum-zacapa', 'jardins', 'Rhum Zacapa', 10, 'Rhum guatémaltèque vieilli en altitude.', '6cl', 'Alcools', NULL, ARRAY['Premium']::TEXT[], true, 124),
('alc-get-27', 'jardins', 'Get 27', 8, 'Liqueur de menthe glaciale.', '6cl', 'Alcools', NULL, ARRAY[]::TEXT[], true, 125),
('whisky-jb', 'jardins', 'JB', 7, 'Blended scotch whisky, doux et accessible.', '4cl', 'Whisky', NULL, ARRAY[]::TEXT[], true, 140),
('whisky-johnny', 'jardins', 'Johnny Walker', 7, 'Red Label, blend mondialement reconnu.', '4cl', 'Whisky', NULL, ARRAY[]::TEXT[], true, 141),
('whisky-talisker', 'jardins', 'Talisker', 10, 'Single malt de l''île de Skye, tourbé & marin.', '4cl', 'Whisky', NULL, ARRAY['Premium']::TEXT[], true, 142),
('whisky-bulleit', 'jardins', 'Bulleit Bourbon', 12, 'Bourbon du Kentucky, notes épicées.', '4cl', 'Whisky', NULL, ARRAY['Premium']::TEXT[], true, 143),
('whisky-clynelish', 'jardins', 'Clynelish', 13, 'Single malt des Highlands, cireux et complexe.', '4cl', 'Whisky', NULL, ARRAY['Premium']::TEXT[], true, 144),
('whisky-lagavulin', 'jardins', 'Lagavulin', 13, 'Single malt d''Islay, intensément tourbé.', '4cl', 'Whisky', NULL, ARRAY['Premium']::TEXT[], true, 145),
('whisky-shooters', 'jardins', 'Shooters', 3, 'Shooter au choix selon arrivage.', '3cl', 'Whisky', NULL, ARRAY[]::TEXT[], true, 146),
('btl-vodka-smirnoff', 'jardins', 'Vodka Smirnoff', 90, 'Bouteille entière pour la table.', '70cl', 'Bouteilles', NULL, ARRAY['À partager']::TEXT[], true, 160),
('btl-get-27', 'jardins', 'Get 27', 90, 'Bouteille de Get 27 menthe glaciale.', '70cl', 'Bouteilles', NULL, ARRAY['À partager']::TEXT[], true, 161),
('btl-rhum-captain', 'jardins', 'Rhum Captain Morgan', 90, 'Bouteille de rhum épicé.', '70cl', 'Bouteilles', NULL, ARRAY['À partager']::TEXT[], true, 162),
('btl-gin-tanqueray', 'jardins', 'Gin Tanqueray', 120, 'Gin London Dry premium.', '70cl', 'Bouteilles', NULL, ARRAY['Premium','À partager']::TEXT[], true, 163),
('btl-jb', 'jardins', 'JB Whisky', 90, 'Bouteille de blended scotch JB.', '70cl', 'Bouteilles', NULL, ARRAY['À partager']::TEXT[], true, 164),
('btl-johnny', 'jardins', 'Johnny Walker', 90, 'Bouteille de Johnny Walker Red.', '70cl', 'Bouteilles', NULL, ARRAY['À partager']::TEXT[], true, 165),
('champ-gobillard-coupe', 'jardins', 'JM Gobillard & Fils Brut — Coupe', 10, 'Champagne Brut, fines bulles, fraîcheur florale.', '12cl', 'Champagnes', NULL, ARRAY[]::TEXT[], true, 180),
('champ-gobillard-btl', 'jardins', 'JM Gobillard & Fils Brut — Bouteille', 90, 'Bouteille de champagne JM Gobillard Brut.', '75cl', 'Champagnes', NULL, ARRAY[]::TEXT[], true, 181),
('champ-epc-coupe', 'jardins', 'EPC Brut — Coupe', 14, 'Champagne EPC Brut, élégant et vif.', '12cl', 'Champagnes', NULL, ARRAY[]::TEXT[], true, 182),
('champ-epc-btl', 'jardins', 'EPC Brut — Bouteille', 120, 'Bouteille EPC Brut.', '75cl', 'Champagnes', NULL, ARRAY['Premium']::TEXT[], true, 183),
('champ-epc-bdn', 'jardins', 'EPC Blanc de Noir', 130, 'Bouteille EPC Blanc de Noir, vineux et structuré.', '75cl', 'Champagnes', NULL, ARRAY['Premium']::TEXT[], true, 184),
('champ-epc-bdb', 'jardins', 'EPC Blanc de Blancs', 140, 'Bouteille EPC Blanc de Blancs, 100% chardonnay.', '75cl', 'Champagnes', NULL, ARRAY['Premium']::TEXT[], true, 185),
('champ-jeeper-coupe', 'jardins', 'Jeeper Blanc de Blancs — Coupe', 13, 'Champagne Jeeper, chardonnay pur, minéralité fine.', '12cl', 'Champagnes', NULL, ARRAY[]::TEXT[], true, 186),
('champ-jeeper-btl', 'jardins', 'Jeeper Blanc de Blancs — Bouteille', 110, 'Bouteille Jeeper Blanc de Blancs.', '75cl', 'Champagnes', NULL, ARRAY[]::TEXT[], true, 187),
('champ-jeeper-magnum', 'jardins', 'Jeeper Blanc de Blancs — Magnum', 160, 'Magnum Jeeper Blanc de Blancs, pour les grandes tablées.', '1.5L', 'Champagnes', NULL, ARRAY['Premium','À partager']::TEXT[], true, 188),
('vin-rouge-vdf-souvenir-verre', 'jardins', 'VDF Souvenir Pinot Noir Dom Paquet — Verre', 5, 'Vin de France, pinot noir souple et fruité.', '12cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 200),
('vin-rouge-vdf-souvenir-btl', 'jardins', 'VDF Souvenir Pinot Noir Dom Paquet — Bouteille', 20, 'Bouteille du même pinot noir.', '75cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 201),
('vin-rouge-macon-verre', 'jardins', 'Bourgogne — Mâcon Perraud (Verre)', 8, 'Vin de France, pinot noir souple et fruité.', '12cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 202),
('vin-rouge-macon-btl', 'jardins', 'Bourgogne — Mâcon Perraud (Bouteille)', 39, 'Bouteille Mâcon Perraud.', '75cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 203),
('vin-rouge-mercurey-btl', 'jardins', 'Bourgogne — Mercurey Vieilles Vignes Dom Theulot 2023', 65, 'Mercurey, vieilles vignes, structure noble.', '75cl', 'Vin Rouge', NULL, ARRAY['Premium']::TEXT[], true, 204),
('vin-rouge-sancerre-btl', 'jardins', 'Loire — Sancerre Classic Pinot Noir BIO Dom Berthier', 60, 'Sancerre BIO, pinot noir tendu et précis.', '75cl', 'Vin Rouge', NULL, ARRAY['BIO']::TEXT[], true, 205),
('vin-rouge-chantecotes-verre', 'jardins', 'Vallée du Rhône — Les Terres Vierges Chantecôtes BIO (Verre)', 6, 'Côtes du Rhône BIO, fruits noirs et garrigue.', '12cl', 'Vin Rouge', NULL, ARRAY['BIO']::TEXT[], true, 206),
('vin-rouge-chantecotes-btl', 'jardins', 'Vallée du Rhône — Les Terres Vierges Chantecôtes BIO (Btl)', 30, 'Bouteille Chantecôtes BIO.', '75cl', 'Vin Rouge', NULL, ARRAY['BIO']::TEXT[], true, 207),
('vin-rouge-cairanne-verre', 'jardins', 'Vallée du Rhône — Cru Cairanne Dom Chantecôtes (Verre)', 7, 'Cairanne, cru du Rhône puissant et épicé.', '12cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 208),
('vin-rouge-cairanne-btl', 'jardins', 'Vallée du Rhône — Cru Cairanne Dom Chantecôtes (Btl)', 35, 'Bouteille Cru Cairanne.', '75cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 209),
('vin-rouge-stjoseph-btl', 'jardins', 'Vallée du Rhône — St Joseph Amphore Or l''Arzelle Vins de Vienne', 65, 'St Joseph en amphore, Syrah pure et minérale.', '75cl', 'Vin Rouge', NULL, ARRAY['Premium']::TEXT[], true, 210),
('vin-rouge-haut-medoc-btl', 'jardins', 'Bordeaux — Haut Médoc Closerie de Camensac 2016', 49, 'Haut Médoc 2016, mature et élégant.', '75cl', 'Vin Rouge', NULL, ARRAY[]::TEXT[], true, 211),
('vin-rouge-stemilion-btl', 'jardins', 'Bordeaux — St Émilion Grand Cru Tauzinat Hermitage 2020', 55, 'St Émilion Grand Cru, rond et soyeux.', '75cl', 'Vin Rouge', NULL, ARRAY['Premium']::TEXT[], true, 212),
('vin-rouge-stjulien-btl', 'jardins', 'Bordeaux — St Julien Fief de Lagrange 2021', 75, 'St Julien 2021, second vin du Château Lagrange.', '75cl', 'Vin Rouge', NULL, ARRAY['Premium']::TEXT[], true, 213),
('vin-blanc-igp-pontons-verre', 'jardins', 'Atlantique — IGP Pontons du Ferret Sauvignon ADVINI (Verre)', 5, 'Sauvignon vif et aromatique.', '12cl', 'Vin Blanc', NULL, ARRAY[]::TEXT[], true, 230),
('vin-blanc-igp-pontons-btl', 'jardins', 'Atlantique — IGP Pontons du Ferret Sauvignon (Btl)', 20, 'Bouteille du même sauvignon.', '75cl', 'Vin Blanc', NULL, ARRAY[]::TEXT[], true, 231),
('vin-blanc-igp-stguilhem-verre', 'jardins', 'Languedoc — IGP St Guilhem Viognier Terroir Tradition (Verre)', 6, 'Viognier, fruits blancs et fleurs.', '12cl', 'Vin Blanc', NULL, ARRAY[]::TEXT[], true, 232),
('vin-blanc-igp-stguilhem-btl', 'jardins', 'Languedoc — IGP St Guilhem Viognier (Btl)', 30, 'Bouteille du Viognier St Guilhem.', '75cl', 'Vin Blanc', NULL, ARRAY[]::TEXT[], true, 233),
('vin-blanc-chardonnay-verre', 'jardins', 'Loire — L''Instant Chardonnay Dom Berthier (Verre)', 7, 'Chardonnay de Loire, rond et tendu.', '12cl', 'Vin Blanc', NULL, ARRAY[]::TEXT[], true, 234),
('vin-blanc-chardonnay-btl', 'jardins', 'Loire — L''Instant Chardonnay Dom Berthier (Btl)', 35, 'Bouteille L''Instant Chardonnay.', '75cl', 'Vin Blanc', NULL, ARRAY[]::TEXT[], true, 235),
('vin-rose-pontons-verre', 'jardins', 'Atlantique — IGP Pontons du Ferret Rosé (Verre)', 5, 'Rosé léger, fruits rouges frais.', '12cl', 'Vin Rosé', NULL, ARRAY[]::TEXT[], true, 250),
('vin-rose-pontons-btl', 'jardins', 'Atlantique — IGP Pontons du Ferret Rosé (Btl)', 20, 'Bouteille du même rosé.', '75cl', 'Vin Rosé', NULL, ARRAY[]::TEXT[], true, 251),
('vin-rose-oh-lala-verre', 'jardins', 'Languedoc — IGP Oc Oh La La (Verre)', 6, 'Rosé fruité du Languedoc.', '12cl', 'Vin Rosé', NULL, ARRAY[]::TEXT[], true, 252),
('vin-rose-oh-lala-btl', 'jardins', 'Languedoc — IGP Oc Oh La La (Btl)', 30, 'Bouteille IGP Oc Oh La La.', '75cl', 'Vin Rosé', NULL, ARRAY[]::TEXT[], true, 253),
('vin-rose-stroch-verre', 'jardins', 'Provence — AOP Provence St Roch (Verre)', 7, 'Rosé de Provence, élégant et sec.', '12cl', 'Vin Rosé', NULL, ARRAY[]::TEXT[], true, 254),
('vin-rose-stroch-btl', 'jardins', 'Provence — AOP Provence St Roch (Btl)', 35, 'Bouteille St Roch.', '75cl', 'Vin Rosé', NULL, ARRAY[]::TEXT[], true, 255),
('pazzo-bambino', 'pazzo', 'Bambino', 6, 'Demi Panuozzo Marguerita.', NULL, 'Menu Enfant', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=600&fit=crop', ARRAY['Kids -12 ans']::TEXT[], true, 1),
('pazzo-charcuterie', 'pazzo', 'Assiette Charcuterie', 10, 'Assortiments de charcuterie italienne.', NULL, 'Antipasti', 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=600&h=600&fit=crop', ARRAY['À partager']::TEXT[], true, 10),
('pazzo-complete', 'pazzo', 'Assiette Complète', 19.5, 'Assortiments de charcuterie et fromage.', NULL, 'Antipasti', 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=600&h=600&fit=crop', ARRAY['À partager']::TEXT[], true, 11),
('pazzo-stracciatella', 'pazzo', 'Stracciatella di Burrata', 13.9, 'Cœur de Burrata servi avec foccacia.', NULL, 'Antipasti', 'https://images.unsplash.com/photo-1633436374961-09b92742047b?w=600&h=600&fit=crop', ARRAY['Signature']::TEXT[], true, 12),
('pazzo-apero-foccacia', 'pazzo', 'Apéro Foccacia', 8.9, 'Concassé de tomates à l''ail, basilic et parmesan, légumes grillés ou jambon de Parme.', NULL, 'Antipasti', 'https://images.unsplash.com/photo-1620577375080-e0517dabd76e?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 13),
('pazzo-salade-little-italy', 'pazzo', 'Salade Little Italy', 15.9, 'Roquette, riz venere, jambon de parme, légumes grillés, tomates cerises, stracciatella di Burrata.', NULL, 'Salades', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 20),
('pazzo-salade-rosmarino', 'pazzo', 'Salade Rosmarino', 15.9, 'Roquette, riz venere, légumes grillés, tomates cerises, chèvre, miel, romarin.', NULL, 'Salades', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=600&fit=crop', ARRAY['Végé ✨']::TEXT[], true, 21),
('pazzo-marguerita', 'pazzo', 'Marguerita', 9.9, 'Sauce tomate, mozzarella, basilic, légumes grillés.', NULL, 'Panuozzo', 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 30),
('pazzo-regina', 'pazzo', 'Regina', 13.5, 'Sauce tomate, mozzarella, basilic, champignons, jambon blanc, légumes grillés.', NULL, 'Panuozzo', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 31),
('pazzo-pistacchio', 'pazzo', 'Pistacchio', 16.9, 'Mayonnaise à la pistache, jambon blanc, stracciatella di Burrata, légumes grillés.', NULL, 'Panuozzo', 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&h=600&fit=crop', ARRAY['Signature']::TEXT[], true, 32),
('pazzo-trufolino', 'pazzo', 'Trufolino', 17.5, 'Mayonnaise à la truffe, crème de truffe, jambon blanc, stracciatella di Burrata, légumes grillés.', NULL, 'Panuozzo', 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&h=600&fit=crop', ARRAY['Signature','Premium']::TEXT[], true, 33),
('pazzo-nutella', 'pazzo', 'Nutella', 12.9, 'Nutella, Speculoos et noisettes torréfiées.', NULL, 'Desserts', 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 40),
('pazzo-tiramisu', 'pazzo', 'Tiramisu', 6.5, 'Tiramisu maison, saveur au choix.', NULL, 'Desserts', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&h=600&fit=crop', ARRAY['Maison']::TEXT[], true, 41),
('cantina-kids', 'cantina', 'Kids', 6, '2 minis chicken cheese servi avec frites.', NULL, 'Menu Enfant', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=600&fit=crop', ARRAY['Kids -12 ans']::TEXT[], true, 1),
('cantina-wings', 'cantina', 'Chicken Wings x5', 7, '5 ailes de poulet, sauce au choix.', NULL, 'Finger Food', 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 10),
('cantina-planche', 'cantina', 'Planche Cantina', 14.9, 'Chicken wings, mozza sticks, onion rings, frites maison.', NULL, 'Finger Food', 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f9c?w=600&h=600&fit=crop', ARRAY['À partager']::TEXT[], true, 11),
('cantina-trilogie', 'cantina', 'Trilogie de Mini Burger', 20, 'Viande au choix, Cheese Classic, Cheese Bacon, Honey Brooklyn.', NULL, 'Finger Food', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=600&fit=crop', ARRAY['Signature','À partager']::TEXT[], true, 12),
('cantina-cheese-classic', 'cantina', 'Cheese Classic', 14.9, 'Viande au choix, sauce california burger, pickles, salade, tomates, oignons, slice de cheddar.', NULL, 'Burgers', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 20),
('cantina-cheese-bacon', 'cantina', 'Cheese Bacon', 16, 'Viande au choix, sauce california burger, pickles, salade, tomates, oignons, slice de cheddar, bacon.', NULL, 'Burgers', 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 21),
('cantina-honey-brooklyn', 'cantina', 'Honey Brooklyn', 16.9, 'Viande au choix, mayo aïl et herbes, salade, tomates, fromage de chèvre, thym et miel.', NULL, 'Burgers', 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=600&h=600&fit=crop', ARRAY['Signature']::TEXT[], true, 22),
('cantina-wrap-honey', 'cantina', 'Wrap Honey Brooklyn', 14.9, 'Poulet frit, mélange de crudités, mayo aïl et herbes, fromage de chèvre, thym et miel. Servi avec frites.', NULL, 'Wraps', 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 30),
('cantina-wrap-bacon', 'cantina', 'Wrap Chicken Bacon', 13, 'Poulet frit, mélange de crudités, sauce california burger, cheddar, bacon et oignons frits. Servi avec frites.', NULL, 'Wraps', 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 31),
('cantina-cesar', 'cantina', 'Salade César', 14.9, 'Salade iceberg, poulet croustillant, tomates cerises, parmesan, œuf, croûtons, sauce césar.', NULL, 'Salades & Plats', 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 40),
('cantina-fish-chips', 'cantina', 'Fish''n''Chips', 16, 'Pavé de cabillaud pané servi avec frites et sauce tartare.', NULL, 'Salades & Plats', 'https://images.unsplash.com/photo-1579208030886-b937da0925dc?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 41),
('cantina-frites', 'cantina', 'Frites Maison', 5, 'Frites maison croustillantes (supplément cheddar +1,5€).', NULL, 'Sides & Desserts', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 50),
('cantina-pancakes', 'cantina', 'Pancakes', 6.5, 'Pancakes moelleux, Nutella ou sirop d''érable au choix.', NULL, 'Sides & Desserts', 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 51),
('saigon-kids', 'saigon', 'Kids — Poulet frit & Riz', 6, 'Poulet frit servi avec riz blanc.', NULL, 'Menu Enfant', 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&h=600&fit=crop', ARRAY['Kids -12 ans']::TEXT[], true, 1),
('saigon-nems-poulet', 'saigon', 'Nems Poulet x3', 6.5, '3 nems croustillants au poulet et légumes.', NULL, 'Tapas', 'https://images.unsplash.com/photo-1606755962773-d324e2dabd62?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 10),
('saigon-beignets-legumes', 'saigon', 'Beignets de Légumes x6', 5, '6 beignets de légumes frits, croustillants à souhait.', NULL, 'Tapas', 'https://images.unsplash.com/photo-1625938144723-13591c2c61f3?w=600&h=600&fit=crop', ARRAY['Végé ✨']::TEXT[], true, 11),
('saigon-beignets-crevettes', 'saigon', 'Beignets de Crevettes x3', 6.5, '3 beignets de crevettes en pâte tempura.', NULL, 'Tapas', 'https://images.unsplash.com/photo-1625944525200-0e85aa31de14?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 12),
('saigon-poulet-frit', 'saigon', 'Poulet Frit 100g', 7, '100g de poulet frit mariné, croustillant et juteux.', NULL, 'Tapas', 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 13),
('saigon-planche', 'saigon', 'Planche Ô Saigon', 15, 'Nems poulet, beignets de légumes, beignets de crevettes, poulet frit.', NULL, 'Tapas', 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&h=600&fit=crop', ARRAY['À partager','Signature']::TEXT[], true, 14),
('saigon-salade-viet', 'saigon', 'Salade Viet', 12, 'Salade vietnamienne fraîche, herbes, vermicelles et sauce nuoc-mâm.', NULL, 'Plats', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=600&fit=crop', ARRAY['Végé ✨']::TEXT[], true, 20),
('saigon-bobun', 'saigon', 'Bobun', 14, 'Bol de vermicelles, herbes fraîches, légumes croquants, viande au choix.', NULL, 'Plats', 'https://images.unsplash.com/photo-1583224994076-ae7e1ae0c1bd?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 21),
('saigon-bobun-crevettes', 'saigon', 'Bobun Crevettes', 16, 'Bol de vermicelles, herbes fraîches, légumes croquants et crevettes sautées.', NULL, 'Plats', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=600&fit=crop', ARRAY[]::TEXT[], true, 22),
('saigon-porc-caramel', 'saigon', 'Porc au Caramel', 15, 'Émincés de porc mijotés au caramel sucré-salé, riz parfumé.', NULL, 'Plats', 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&h=600&fit=crop', ARRAY['Signature']::TEXT[], true, 23),
('saigon-fruits-exotiques', 'saigon', 'Salade de Fruits Exotiques', 6, 'Mangue, ananas, fruits de la passion, citron vert.', NULL, 'Desserts', 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&h=600&fit=crop', ARRAY['Végé ✨']::TEXT[], true, 30),
('saigon-nem-banane', 'saigon', 'Nem Banane Nutella x2', 8, '2 nems frits banane et Nutella, dessert gourmand.', NULL, 'Desserts', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&h=600&fit=crop', ARRAY['Best-Seller 🔥']::TEXT[], true, 31)
ON CONFLICT (id) DO NOTHING;
