// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzmmsitzxxalvojxncmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bW1zaXR6eHhhbHZvanhuY21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5MzU1ODgsImV4cCI6MjA5MjUxMTU4OH0.cbsjAmgwOQgB86pNMovbwZWLzMsor3fo1BkuIsLl-TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    // Heartbeat élargi pour économiser la batterie des téléphones clients
    // (la latence des broadcasts/changes reste sub-seconde, < 500ms en pratique)
    heartbeatIntervalMs: 30000,
    // Backoff progressif sur reconnect : 1s → 2s → 4s → 8s
    reconnectAfterMs: (tries: number) => Math.min(1000 * Math.pow(2, tries - 1), 8000),
    params: { eventsPerSecond: 10 },
  },
});
